spring:
  redis:
    uri: redis-cli -u redis://default:WxyS6jJCyFRSBvowpJmDcExleAe9aDOx@redis-13978.c258.us-east-1-4.ec2.redns.redis-cloud.com:13978
  #    host: localhost

  #    port: 6379

  data:
    mongodb:
      uri: mongodb+srv://sawan:bMByWVBGr20NJy6u@cluster0.bp7ffuu.mongodb.net/?retryWrites=true&w=majority&appName=Journal_App
      database: journaldb
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: sawankushwaha222@gmail.com
    password: wkyn mlzf rgzr oomu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /journal