spring:
  data:
    mongodb:
      uri: mongodb+srv://sawan:bMByWVBGr20NJy6u@cluster0.bp7ffuu.mongodb.net/?retryWrites=true&w=majority&appName=Journal_App
      database: journaldb
      auto-index-creation: true

server:
  port: 8081
  servlet:
    context-path: /journal